#!/bin/bash

#Call from directory containg csvs
#Feed this in at the end of WDranker to make the PDF

while getopts ":s:b:t:g" opt; do
	case $opt in 
	  s) source="$OPTARG"
	  ;;
 	  b) band="$OPTARG"
	  ;;
  	  t) sampling="$OPTARG"
	  ;;
  	  g) generate=1
	  ;;
  	  \?) echo "Invalid option -$OPTARG" >&2
  	  ;;
	esac
done

if [ $generate -eq 1 ] 2>/dev/null;
then
	firstfile=$(ls -v PDFs/*.pdf | head -1)
	outputname=$(echo $firstfile | cut -f1 -d"_")all.pdf
	pdfunite $(ls -v PDFs/*.pdf) $outputname
else
	#Case with brakets first
	if [[ $source = *"["* ]]; then

		source2="$(sed 's/[][]/\\&/g' <<< "${source}")"
		[ -f PDFs/${source2}_${band}_${sampling}_combined.pdf ]  && rm -f PDFs/${source2}_${band}_${sampling}_combined.pdf

		pdfunite $(ls -v PDFs/${source2}-${band}-${sampling}*.pdf) PDFs/${source2}_${band}_${sampling}_combined.pdf

		rm -f PDFs/${source2}-${band}-${sampling}*.pdf

	else

		[ -f PDFs/${source}_${band}_${sampling}_combined.pdf ]  && rm -f PDFs/${source}_${band}_${sampling}_combined.pdf

		pdfunite $(ls -v PDFs/${source}-${band}-${sampling}*.pdf) PDFs/${source}_${band}_${sampling}_combined.pdf

		rm -f PDFs/${source}-${band}-${sampling}*.pdf

	fi
fi
