#!/bin/bash

#Call from directory containg csvs
#Feed this in at the end of WDranker to make the PDF

while getopts ":s:b:" opt; do
	case $opt in 
	  s) source="$OPTARG"
	  ;;
 	  b) band="$OPTARG"
	  ;;
  	  \?) echo "Invalid option -$OPTARG" >&2
  	  ;;
	esac
done
#Case with brakets first
if [[ $source = *"["* ]]; then

	source2="$(sed 's/[][]/\\&/g' <<< "${source}")"
	[ -f PDFs/${source2}_${band}_combined.pdf ]  && rm -f PDFs/${source2}_${band}_combined.pdf

	pdfunite $(ls -v PDFs/${source2}-${band}*.pdf) PDFs/${source2}_${band}_combined.pdf

	rm -f PDFs/${source2}-${band}*.pdf

else

	[ -f PDFs/${source}_${band}_combined.pdf ]  && rm -f PDFs/${source}_${band}_combined.pdf

	pdfunite $(ls -v PDFs/${source}-${band}*.pdf) PDFs/${source}_${band}_combined.pdf

	rm -f PDFs/${source}-${band}*.pdf



fi
